app = 'manivilization'
primary_region = 'iad'

[build]
image = 'registry.fly.io/manivilization:latest'

[deploy]
release_command = 'run -A migrate.ts migrate migrations/'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
