name: Development

on:
  pull_request:
    branches: [master]
  merge_group:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          diagnostic-endpoint:
          use-flakehub: false

      - name: Evaluate Nix checks
        run: nix flake check
